### ISSUE TITLE
Setting environment variable does not work

### ISSUE THREAD

**Issue by AdiIntel** [trond-snekvik/vscode-kconfig#2]
Really love the kconfig integration in VC code, works great for zephyr. 

Below workspace configuration setting does NOT work: 
`${env:HOME}/zephyrdir/zephyr_fork`

however, this one does: 
`/home/<username>/zephyrdir/zephyr_fork`

Also, the setting change take effect only when editor start fresh.

**Comment by trond-snekvik** [comment]
Thanks for reporting! 
The environment variable variant of the variable substitution isn't supported, but it definitely should be, so I marked it as an enhancement. I'll try pushing an update for this this week.

**Comment by AdiIntel** [comment]
Same goes for your other awesome extension - [DeviceTree](https://marketplace.visualstudio.com/items?itemName=trond-snekvik.devicetree).
