### ISSUE TITLE
Option to add custom board

### ISSUE THREAD

**Issue by ycsin** [trond-snekvik/vscode-kconfig#3]
First and foremost, its a really great extension, thanks for the good work!

I wonder if there's anyway to include custom board?

I have my custom board in another folder (the GitLab repo is 'boards')for the ease of maintenance like so:
`C:\Users\yongc\GitLab\boards\boards\arm\ivm22_f103re`

I'm not sure if this configuration is supposed to be used as such, but I configured the extension like so:
![image](https://user-images.githubusercontent.com/1563974/109787487-3d6de080-7c49-11eb-8e77-03ed0e96fd71.png)

But nothing changed.

**Comment by ycsin** [comment]
For some reason the extension is notifying me of an error today which allow me to fix it and it now seems to be working!

**Comment by trond-snekvik** [comment]
Generally, you should select the board using the "Kconfig: set board for Zephyr" command, which uses west's logic for finding the board, and manually modifying the board setting is a bit of a fallback option. Sounds like there might be some glitches in the manual editing, but good to hear that this works for you now.
