### ISSUE TITLE
Can't find west on Windows

### ISSUE THREAD

**Issue by wldevries** [trond-snekvik/vscode-kconfig#4]
I'm probably doing something wrong, but vscode-kconfig is unable to find west. I have the `west` setting set to `C:\Python39\Scripts`, which is where pip installed `west.exe`. `Base` is set `E:\Dev\zephyr\zephyrproject\zephyr`. I've tried all sorts of other combinations but nothings seems to work.

I'm using v1.1.8 on VS Code 1.54.1

**Comment by ycsin** [comment]
Hey, I think you need to specify `west.exe` (ie `C:\Python39\Scripts\west.exe`), your `Base` is correct.
